# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: de

pipeline:
# some messages might receive a low classification confidence. FallbackClassifier helps to handle
# out-of-scope messages gracefully
  # - name: FallbackClassifier
   #  threshold: 0.7
   - name: WhitespaceTokenizer
   - name: LexicalSyntacticFeaturizer
   - name: CountVectorsFeaturizer
   - name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
   - name: DIETClassifier
     epochs: 100
     entity_recognition: False
   - name: RegexEntityExtractor
     use_lookup_tables: True

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
  - name: RulePolicy
#  - name: UnexpectedTEDIntentPolicy
  - name: TEDPolicy
    constrain_similarities: true
    max_history: 5
    epochs: 100
#     max_history: 5
#     epochs: 100
# - name: FormPolicy

